# SwiftLint Configuration for Grid Project
# https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - Sources

excluded:
  - .build
  - Test
  - Scripts
  - Grid.xcodeproj
  - .trunk

# Rule configuration
disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_first_last
  - vertical_parameter_alignment_on_call

# Rule parameters
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

# Reporter type
reporter: "xcode"

